version: '3.8'
services:
  postgres:
    image: postgres:12
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - gqldemo

  pgadmin:
    links:
      - postgres:postgres
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - pgadmindata:/var/lib/pgadmin
    env_file:
      - docker.env
    networks:
      - gqldemo

networks:
  gqldemo:
    driver: bridge
volumes:
  postgresdata:
    driver: local
  pgadmindata:
    driver: local
